### ISSUE TITLE
ClientAssertion usage/documentation?

### ISSUE THREAD

**Issue by SpiritBob** [IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection#107]
What exactly is `OAuth2IntrospectionOptions.ClientAssertion` used for and how does one configure it?

If you could show an example, that'd be great.

**Comment by leastprivilege** [comment]
It's for OAuth client assertions - as a replacement for client secrets.

**Comment by ubik** [comment]
Ok, but how should we use it?

We wish to use ClientAssertion with Type = urn:ietf:params:oauth:client-assertion-type:jwt-bearer
How can we dynamically change ClientAssertion.Value with newly signed JwtToken when the old one will be expired?

Or we should create single token with expiration in far future (or without exp claim?) for whole application lifetime?
This doesn't seem more secure than a plain text secret.

Theoretically we could save ClientAssertion or whole Options and update them by timer, but this looks very ugly.
ClientAssertion.Value can't be overridden in a some inheritor because it's not virtual, according to https://github.com/IdentityModel/IdentityModel/pull/291 ValueProvider will not be supported too.
Maybe you could create IClientAssertion interface?

**Comment by leastprivilege** [comment]
I guess the right approach would be to use the event pattern of the authentication handler to provide a callback when an assertion needs to be created.

**Comment by ubik** [comment]
Please review proposed implementation: https://github.com/IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection/pull/122

**Comment by leastprivilege** [comment]
@ubik Have you tested the handler in production? Does it work the way you want it?

**Comment by ubik** [comment]
I can't say about production because we have a standalone product with long development cycle, but it our test environment implementation works well.

**Comment by leastprivilege** [comment]
ok thanks
